# Provision steps:
#
# helm repo add jetstack https://charts.jetstack.io
# helm install cert-manager jetstack/cert-manager --version v0.13.1 --namespace kube-system --values ./cert-manager.yaml
# kubectl apply -f https://raw.githubusercontent.com/jetstack/cert-manager/release-0.13/deploy/manifests/00-crds.yaml --validate=false

global:
  rbac:
    create: true

replicaCount: 1
resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

webhook:
  enabled: true
  replicaCount: 1

  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 50m
      memory: 64Mi

cainjector:
  enabled: true
  replicaCount: 1

  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 20m
      memory: 128Mi